apiVersion: skaffold/v2alpha3
kind: Config
metadata:
  name: loto
build:
  tagPolicy:
    envTemplate:
      template: "{{.IMAGE_NAME}}:{{.IMAGE_TAG}}"
  artifacts:
  - image: loto
    buildpack:
      builder: "cloudfoundry/cnb:tiny"
deploy:
  kubectl:
    manifests:
    - loto-deploy.yaml
